### ISSUE TITLE
Display driver missing for latest Raspbery OS using Kernel 5.15.30-v8+

### ISSUE THREAD

**Issue by MartinVerges** [waveshare/7inch-DSI-LCD-C#7]
Hello,

as requested weeks ago in your support ticket 19101, your display is not working as there is no driver for the current OS release from raspberry. 

We need a driver module (better open source DKMS) for 5.15.30-v8+.

Thanks
Martin

**Comment by waveshare** [comment]
Hello,
We have already replied to you on work order 19101 and attached the driver for the 5.15 kernel. Please go to your email to confirm it. If you have any questions, you can continue to contact us by email.

**Comment by MartinVerges** [comment]
Indeed, sorry I seem to have missed the attachment and just tried a git pull.
